== 贝叶斯理论

=== 一个公式的故事

朴素贝叶斯法利用贝叶斯定理和学到的联合概率模型进行分类预测，是典型的生成模型: +

[stem]
++++
P(Y | X) = \frac{ P( X | Y) P(Y)}{P(X)} = \frac{P(Y) P(X | Y)}{ \sum_{Y} P(Y) P(X | Y)} \hspace{1cm} (11.1)
++++

本章真不知道有啥可讲的，最重要的公式(11.1)，虽然很简单，用处却很大，会用它最重要。 +

通过计算输入\(x\)分到后验概率最大的类别\(y\)，就得到对输入的正确估计和分类。 +

=== 一些常见题目

==== 两信封和美元的问题

**1.问题描述:** +

有左右两个信封，其中左边信封里有一美元，右边信封里没有钱，有美元的信封里有四个球：两个红球和两个黑球；
没有美元的信封里有三个球：一个红球，两个黑球。 +

问：从一个信封里，随机取一个球，如果这个球是黑球，那么问你这个信封里有美元的概率是多少？如果取出的球是红球，这个信封里有美元的概率又是多少? +

首先对问题进行数学建模: +
--
* \(c1,c2\)分别表示左右两个信封
* \(p(B), p( R )\)分别表示摸到黑球和摸到红球的概率
--

根据题目，可以得到如下公式: +

\begin{align}
p(c1) = p(c2) & = \frac{1}{2} \\
p(R | c1) & = \frac{1}{2} \\
p(B | c1) & = \frac{1}{2} \\
p(R | c2) & = \frac{1}{3} \\
p(B | c2) & = \frac{2}{3} \\
p( R ) = p(R | c1) p(c1) & + p( R | c2) p(c2) = \frac{1}{2} * \frac{1}{2} + \frac{1}{3} * \frac{1}{2} =  \frac{5}{12} \\
p(B) = p(B | c1) p(c1) & + p(B | c2) p(c2) = \frac{1}{2} * \frac{1}{2} + \frac{2}{3} * \frac{1}{2} =  \frac{7}{12}
\end{align}

那么要求的分别是\(p(c1 | B), p(c1 | R)\)，则: +

\begin{align}
p(c1 | B) = \frac{p(c1) p(B | c1)}{p(B)} = \frac{ \frac{1}{2} * \frac{1}{2}}{ \frac{7}{12} } = \frac{3}{7} \\
p(c1 | R) = \frac{p(c1) p(R | c1)}{p( R )} = \frac{ \frac{1}{2} * \frac{1}{2}}{ \frac{5}{12} } = \frac{3}{5}
\end{align}

结论：如果摸到黑球，则该信封里有美元的概率为\(\frac{3}{7}\)；如果摸到红球，则该信封里有美元的概率为\(\frac{3}{5}\) +

==== 三扇门和开奖的问题

这是个国外经典的游戏叫: `Monty Hall`。 +
**2.问题描述** +

有三扇门，其中只有一扇门里有惊喜，你可以先选一扇门你认为有惊喜的门，开奖人员不会打开你选的那扇门，他会从剩余两扇门里打开一个没有惊喜的门，然后问你，要不要换。 +

首先对问题进行建模，给三扇门进行编号，假定你选择的是1号门，\(H=i\)表示第\(i\)扇门后有惊喜，\(D=i\)表示在你选择1号门后，开奖人员打开了某扇门的编号，
假定开奖人员打开了3号门，则问题变为求\(p(H | D=3) = ?\),由已知条件可知： +
--
* \(p(H=1) = p(H=2) = p(H=3) = \frac{1}{3}\)
* \(p(D=2 | H =1) = \frac{1}{2}, \hspace{1cm} p(D=3 | H = 1) = \frac{1}{2} \)
* \(p(D=2 | H =2) = 0, \hspace{1cm} p(D=3 | H=2) = 1 \)
* \(p(D=2 | H =3) = 1, \hspace{1cm} p(D=3 | H=3) = 0\)
--

那么: +
\begin{align}
p(H = 1 | D = 3) & = \frac{ p(D=3 | H =1) p(H=1) }{p(D = 3)} = \frac{ \frac{1}{2} \cdot \frac{1}{3} }{ \frac{1}{3} \cdot \frac{1}{2} + \frac{1}{3} \cdot 1 + \frac{1}{3} \cdot 0 } = \frac{1}{3} \\
p(H = 2 | D = 3) & = 1 - p(H = 1 | D = 3) = \frac{2}{3}
\end{align}

结论：应该去选择第2扇门，中奖概率大些。 +
